-- AlterTable
ALTER TABLE "signals" ADD COLUMN IF NOT EXISTS "position_amount" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "simulated_margin" DOUBLE PRECISION DEFAULT 10.0,
ADD COLUMN IF NOT EXISTS "realized_pnl_usd" DOUBLE PRECISION;
